### ISSUE TITLE
Problem with master compile sh script

### ISSUE THREAD

**Issue by jeroen-nl** [KickerTom/openhr20#1]
Hello,

I get a lot of compile errors when using /openhr20/rfmsrc/master$ ./compile_arduino.sh.
Is there a other way I need to compile?

Thanks in advance.

ERROR:
-----------
osboxes@osboxes:~/openhr20/rfmsrc/master$ ./compile_arduino.sh 

-------- begin --------

Cleaning project:
rm -f master.hex
rm -f master.eep
rm -f master.bin
rm -f master.cof
rm -f master.elf
rm -f master.map
rm -f master.sym
rm -f master.lss
rm -f master.txt
rm -f obj/main.o obj/com.o obj/queue.o
rm -f obj/main.lst obj/com.lst obj/queue.lst
rm -f obj/rtc.o obj/cmac.o obj/eeprom.o obj/rfm.o obj/rs232_485_hw.o obj/wireless.o
rm -f obj/rtc.lst obj/cmac.lst obj/eeprom.lst obj/rfm.lst obj/rs232_485_hw.lst obj/wireless.lst
rm -f obj/xtea-asm.o
rm -f obj/xtea-asm.lst
rm -f main.s com.s queue.s
rm -f main.d com.d queue.d
rm -f main.i com.i queue.i
rm -rf .dep
-------- end --------

-------- begin --------
avr-gcc (GCC) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling C: main.c
avr-gcc -c -mmcu=atmega328p -I. -gdwarf-2 -DF_CPU=10000000UL  -DSECURITY_KEY_0=0x01 -DSECURITY_KEY_1=0x23 -DSECURITY_KEY_2=0x45 -DSECURITY_KEY_3=0x67 -DSECURITY_KEY_4=0x89 -DSECURITY_KEY_5=0x01 -DSECURITY_KEY_6=0x23 -DSECURITY_KEY_7=0x45 -DRFM_FREQ_MAIN=868 -DRFM_FREQ_FINE=0.35 -DRFM_TUNING=1 -DNANODE=0 -DJEENODE=0 -Os -mcall-prologues -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -Wall -Wstrict-prototypes -Wa,-adhlns=obj/main.lst -I.. -std=gnu99 -ffreestanding  -fdata-sections -fno-toplevel-reorder -Wundef -MMD -MP -MF .dep/main.o.d -DMCU=atmega328p -DATMEGA32_DEV_BOARD=0  main.c -o obj/main.o 
main.c:70:2: warning: #warning task variable manipulation is not protected to interrupt, fix it [-Wcpp]
 #warning task variable manipulation is not protected to interrupt, fix it
  ^
In file included from eeprom.h:40:0,
                 from main.c:50:
main.c: In function ‘main’:
rfm_config.h:133:34: error: ‘GICR’ undeclared (first use in this function)
     #define RFM_INT_EN_NOCALL() (GICR |= _BV(INT2))
                                  ^
rfm_config.h:137:23: note: in expansion of macro ‘RFM_INT_EN_NOCALL’
 #define RFM_INT_EN() (RFM_INT_EN_NOCALL(), RFM_INT_vect())
                       ^
main.c:92:5: note: in expansion of macro ‘RFM_INT_EN’
     RFM_INT_EN();
     ^
rfm_config.h:133:34: note: each undeclared identifier is reported only once for each function it appears in
     #define RFM_INT_EN_NOCAT2))
                                  ^
rfm_config.h:137:23: note: in expansion of macro ‘RFM_INT_EN_NOCALL’
 #define RFM_INT_EN() (RFM_INT_EN_NOCALL(), RFM_INT_vect())
                       ^
main.c:92:5: note: in expansion of macro ‘RFM_INT_EN’
     RFM_INT_EN();
     ^
In file included from /usr/lib/avr/include/avr/io.h:99:0,
                 from main.c:37:
rfm_config.h:133:46: error: ‘INT2’ undeclared (first use in this function)
     #define RFM_INT_EN_NOCALL() (GICR |= _BV(INT2))
                                              ^
rfm_config.h:137:23: note: in expansion of macro ‘RFM_INT_EN_NOCALL’
 #define RFM_INT_EN() (RFM_INT_EN_NOCALL(), RFM_INT_vect())
                       ^
main.c:92:5: note: in expansion of macro ‘RFM_INT_EN’
     RFM_INT_EN();
     ^
In file included from eeprom.h:40:0,
                 from main.c:50:
rfm_config.h:137:42: warning: left-hand operand of comma expression has no effect [-Wunused-value]
 #define RFM_INT_EN() (RFM_INT_EN_NOCALL(), RFM_INT_vect())
                                          ^
main.c:92:5: note: in expansion of macro ‘RFM_INT_EN’
     RFM_INT_EN();
     ^
main.c: In function ‘init’:
main.c:257:2: error: ‘DDRA’ undeclared (first use in this function)
  DDRA = _BV(PA2);        //Green LED for Sync
  ^
In file included from /usr/lib/avr/include/avr/io.h:99:0,
                 from main.c:37:
main.c:257:13: error: ‘PA2’ undeclared (first use in this function)LL() (GICR |= _BV(IN
  DDRA = _BV(PA2);        //Green LED for Sync
             ^
main.c:261:5: error: ‘PORTA’ undeclared (first use in this function)
     PORTA = 0xff;
     ^
main.c:289:7: error: ‘MCUCSR’ undeclared (first use in this function)
       MCUCSR |= _BV(ISC2);                // rising edge interrupt
       ^
In file included from /usr/lib/avr/include/avr/io.h:99:0,
                 from main.c:37:
main.c:289:21: error: ‘ISC2’ undeclared (first use in this function)
       MCUCSR |= _BV(ISC2);                // rising edge interrup

**Comment by KickerTom** [comment]
Thank you for reporting this breakage. It seems it was broken for a long time.
Fixed in commit 2a7eda3. Please test and report back. I will then merge to master OpenHR repository.

**Comment by jeroen-nl** [comment]
Seems to be working now :)
Thanks for the fix.

**Comment by KickerTom** [comment]
Thanks for the verification.
